@startuml


Class Juego {
    +update():void
    +gameOver():boole
    +coliciones():void
    +run():void
    
}


package logik{

Juego *-- Pacman
Juego *-- Fantasma
Juego *-- Fruta
Juego *-- Mapa
Juego *-- Pastilla 
Pacman --* Mapa
Fantasma --* Mapa

Class Fantasma {
    velocidad
    posicion_x
    posicion_y    
}
Class Pacman {
    vidas
    velocidad
    posicion_x
    posicion_y
}
Class Fruta {
    puntos
    desaparecer()
}
Class Mapa {
    tablaDePuntos()
}
Class Dots{
}
Class Fentanilo {

}
}
interface Dibujable {
    dibujar()
}
interface Personaje {
    -moverse()
    -morir()
    -matar()
    -resurreccion()
}

Pacman ..|> Dibujable
Fruta ..|> Dibujable
Fantasma ..|> Dibujable
Dots ..|> Dibujable
Fentanilo ..|> Dibujable

Pacman ..|> Personaje 
Fantasma ..|> Personaje

' Personaje 

' Personaje Fantasma



@enduml