@startuml


Class Juego {
    +update() : void
    +gameOver() : bool
    +run(jugar : bool) : void
    
}



Personaje <|-- Pacman
Personaje <|-- Fantasma
Personaje --> Mapa

Juego *-- Personaje
Juego o-- Fruta
Juego *-- Mapa
Juego *-- Pastilla 
Juego *-- Dots

Pacman o-- Pastilla
Pacman o-- Dots
Pacman o-- Fruta
Class Personaje{
    - posicion_x: int
    - posicion_y: int
    + mover(dx: int, dy: int): void
    + verificarColisiones(): void
}
Class Fantasma {
    + velocidad : float  

}
Class Pacman {
    + vidas : int
    + velocidad : float
    + score : int 
    + superPoder(Activo: boolean): void
    + comerPunto(): void
    + comerFruta(): void
    + perderVida(): void

}
Class Fruta {
    + puntos
    + desaparecer()
}
Class Mapa {
    + obtenerContenidoCelda()
    + cargarMapa() : void
    + verificarColisiones(personaje: Personaje): void
}
Class Dots{
    + puntos
    + desaparecer()
}
Class Pastilla {
    + Activo : bool
    + darPoder() : bool

}

interface Dibujable {
    dibujar()
}
interface Animacion {
    moverse()
    morir()
    matar()
    resurreccion()
}
Personaje .|> Animacion 
Personaje ..|> Dibujable
Fruta ..|> Dibujable
Dots ..|> Dibujable
Pastilla ..|> Dibujable
Mapa ..|> Dibujable


Fruta <|-- Cereza
Fruta <|-- Piña
@enduml